### PR TITLE
Support more algorithms (no breaking changes)

### PR DESCRIPTION
**Pull request by hfossli**

### CODE REVIEW

**Review by wuf810 — APPROVED** [review]
Looks good to me.

**Comment by swizzlr** [comment]
I note the RSA algorithms in allAlgorithms - is that deliberate? Do they work with an EC key?

**Comment by hfossli** [comment]
No, you are right, they do not work. That array is a dump of all constants for SecKeyAlgorithm and then I iterate over them to find those that are supported.

**Comment by hfossli** [comment]
Check the function named supportedAlgorithms in Utils.swift

**Comment by swizzlr** [comment]
Sorry, totally lacking coffee. Seems fine!

**Comment by wuf810** [comment]
Hey, I've just checked out the latest master and getting this error:

screen shot 2017-11-15 at 10 59 20

**Comment by hfossli** [comment]
Thanks for letting me know. Fixing this by merging the demo project changes.

**Comment by hfossli** [comment]
Fixed on master. There's some breaking changes on the API level. Will have to bump major version number on next release. I hope it is easier to have control of sha method now.

**Comment by hfossli** [comment]
https://github.com/agens-no/EllipticCurveKeyPair/commit/fd0fe13c7843fdb93e1478abe887657571da6473#diff-e0359a9449187adbaf1fc4ec81b8ba94

**Pull request merged**
